### PR TITLE
Cross build with 2.10 + 2.11

### PR DESCRIPTION
**Pull request by tixxit**
?r @striation 

Cross builds bonsai for both 2.10 and 2.11, rather than just 2.11.

### CODE REVIEW

**Comment by striation** [comment]
:+1: 

Remember that if you want `release` to cross release by default you will need additional settings (of course you can say `release cross` instead).

**Comment by tixxit** [comment]
@striation Yeah - I tried changing the SBT setting for brushfire and it didn't work, so I just use `release cross` all the time now :(

**Comment by striation** [comment]
I think the setting is:

```scala
releaseCrossBuild := true
```

**Comment by tixxit** [comment]
I haven't had success with this (I don't know why).

**Comment by striation** [comment]
OK let's not sweat it for now -- I will look into it later.

**Pull request merged**
